export const LIMITS = {
  REFERENCES_MAX: 200,
  WORKSPACE_SYMBOLS_MAX: 100,
  DIAGNOSTICS_MAX: 500,
  // V3 defaults
  DECLARATION_MAX: 50,
  TYPE_DEFINITION_MAX: 50,
  IMPLEMENTATION_MAX: 100,
  COMPLETION_MAX: 50,
  CALL_HIERARCHY_ITEMS_MAX: 10,
  CALL_HIERARCHY_RESULTS_MAX: 100,
  TYPE_HIERARCHY_ITEMS_MAX: 10,
  TYPE_HIERARCHY_RESULTS_MAX: 100,
  CHANGE_IMPACT_REFS_MAX: 200,
  EXPLAIN_DIAGNOSTICS_MAX: 20,
  TIMEOUTS: {
    HOVER_MS: 3_000,
    DEFINITION_MS: 5_000,
    REFERENCES_MS: 10_000,
    DOCUMENT_SYMBOLS_MS: 5_000,
    WORKSPACE_SYMBOLS_MS: 10_000,
    RENAME_MS: 10_000,
    HEALTH_CHECK_MS: 5_000,
    // V3
    DECLARATION_MS: 5_000,
    TYPE_DEFINITION_MS: 5_000,
    IMPLEMENTATION_MS: 10_000,
    SIGNATURE_HELP_MS: 3_000,
    COMPLETION_MS: 5_000,
    PREPARE_CALL_HIERARCHY_MS: 5_000,
    INCOMING_CALLS_MS: 10_000,
    OUTGOING_CALLS_MS: 10_000,
    PREPARE_TYPE_HIERARCHY_MS: 5_000,
    SUPERTYPES_MS: 10_000,
    SUBTYPES_MS: 10_000,
    ANALYZE_CHANGE_IMPACT_MS: 20_000,
    FIX_DIAGNOSTIC_CANDIDATES_MS: 15_000,
    EXPLAIN_DIAGNOSTICS_MS: 15_000,
  },
} as const;

export function clampResults<T>(arr: T[], max: number): { items: T[]; truncated: boolean; returned: number } {
  if (arr.length <= max) {
    return { items: arr, truncated: false, returned: arr.length };
  }
  return { items: arr.slice(0, max), truncated: true, returned: max };
}